import { QuizQuestion, ExerciseItem } from '../src/types';

export function getRichGroup1Pool(
  lessonNum: number,
  topicId: string,
  titleEn: string,
  titleVi: string,
  q: Function,
  ex: Function
): { questions: QuizQuestion[]; exercises: ExerciseItem[] } {
  const questions: QuizQuestion[] = [];
  const exercises: ExerciseItem[] = [];

  switch (lessonNum) {
    case 1: { // python_foundations
      questions.push(
        q(1, 1, topicId, "Who created Python and in what year was it first released?", "Ai là người sáng tạo ra Python và năm phát hành đầu tiên là năm nào?",
          [["Guido van Rossum in 1991", "Guido van Rossum năm 1991"], ["Dennis Ritchie in 1972", "Dennis Ritchie năm 1972"], ["James Gosling in 1995", "James Gosling năm 1995"], ["Bjarne Stroustrup in 1985", "Bjarne Stroustrup năm 1985"]],
          [0], "Guido van Rossum released Python in 1991 focusing on clean, readable syntax.", "Guido van Rossum phát hành Python năm 1991 nhấn mạnh tính dễ đọc và năng suất.", "easy"),
        q(2, 1, topicId, "What is Python bytecode?", "Bytecode trong Python là gì?",
          [["Platform-independent intermediate code executed by the Python Virtual Machine (PVM)", "Mã trung gian độc lập nền tảng được Máy ảo Python (PVM) thực thi"], ["Direct binary machine code compiled for specific CPU hardware", "Mã máy nhị phân chạy trực tiếp trên phần cứng"], ["The original source code stored in .py files", "Mã nguồn gốc lưu trong tệp .py"], ["A JavaScript representation of Python syntax", "Biểu diễn JavaScript của cú pháp Python"]],
          [0], "Python source code is compiled to intermediate bytecode (.pyc) for the PVM.", "Mã nguồn Python được biên dịch thành bytecode trung gian (.pyc) cho PVM.", "easy"),
        q(3, 1, topicId, "What does REPL stand for in Python development?", "Thuật ngữ REPL trong Python viết tắt của gì?",
          [["Read-Eval-Print Loop", "Read-Eval-Print Loop (Đọc-Đánh giá-In-Lặp lại)"], ["Runtime Evaluation Program Language", "Runtime Evaluation Program Language"], ["Recursive Evaluation Process Logic", "Recursive Evaluation Process Logic"], ["Realtime Environment Parser Level", "Realtime Environment Parser Level"]],
          [0], "REPL stands for Read-Eval-Print Loop, an interactive command-line shell.", "REPL là môi trường dòng lệnh tương tác trực tiếp của Python.", "easy"),
        q(4, 1, topicId, "How are single-line comments written in Python?", "Chú thích dòng đơn trong Python viết như thế nào?",
          [["Using the # character", "Dùng ký tự #"], ["Using // characters", "Dùng ký tự //"], ["Using -- characters", "Dùng ký tự --"], ["Using /* */ delimiters", "Dùng cặp /* */"]],
          [0], "# is used for single-line comments in Python.", "Dấu # dùng cho chú thích dòng đơn.", "easy"),
        q(5, 1, topicId, "What command displays The Zen of Python principles?", "Lệnh nào hiển thị triết lý The Zen of Python?",
          [["import this", "import this"], ["import zen", "import zen"], ["help(zen)", "help(zen)"], ["show_zen()", "show_zen()"]],
          [0], "'import this' triggers Tim Peters' Zen of Python guiding aphorisms.", "'import this' in ra 19 triết lý thiết kế của Python.", "easy"),
        q(6, 1, topicId, "Which file extension is standard for compiled Python bytecode caches?", "Phần mở rộng nào là chuẩn cho tệp bytecode đã biên dịch?",
          [[".pyc", ".pyc"], [".py", ".py"], [".class", ".class"], [".pyd", ".pyd"]],
          [0], ".pyc stores cached compiled bytecode inside the __pycache__ directory.", ".pyc chứa bytecode biên dịch sẵn lưu trong thư mục __pycache__.", "medium"),
        q(7, 1, topicId, "Why does Python use indentation instead of curly braces {}?", "Tại sao Python sử dụng thụt lề thay vì ngoặc nhọn {}?",
          [["To enforce clean visual structure and readability across teams", "Để bắt buộc cấu trúc đồng nhất và dễ đọc giữa các lập trình viên"], ["Because computers parse indentation faster than braces", "Vì máy tính đọc thụt lề nhanh hơn"], ["Because ASCII lacked curly braces when Python was created", "Vì bảng mã ASCII cũ thiếu dấu ngoặc nhọn"], ["Indentation is purely optional in Python", "Thụt lề là tùy chọn"]],
          [0], "Python enforces indentation as syntax to ensure consistently readable codebases.", "Python quy định thụt lề như một cú pháp bắt buộc để mã nguồn luôn dễ đọc.", "medium"),
        q(8, 1, topicId, "What is CPython?", "CPython là gì?",
          [["The reference implementation of Python written in C", "Bản triển khai tham chiếu tiêu chuẩn của Python viết bằng C"], ["A compiler translating C code into Python", "Trình biên dịch mã C sang Python"], ["A Python library for microcontrollers", "Thư viện Python cho vi điều khiển"], ["A closed-source proprietary distribution", "Bản phân phối mã nguồn đóng"]],
          [0], "CPython is the official, standard Python implementation maintained by python.org.", "CPython là bản triển khai tham chiếu chuẩn mực của Python.", "medium"),
        q(9, 1, topicId, "Which built-in function writes text to standard output?", "Hàm tích hợp sẵn nào xuất văn bản ra console?",
          [["print()", "print()"], ["echo()", "echo()"], ["display()", "display()"], ["console.log()", "console.log()"]],
          [0], "print() is the built-in output function in Python.", "print() là hàm xuất dữ liệu có sẵn trong Python.", "easy"),
        q(10, 1, topicId, "What happens when a Python script has a SyntaxError?", "Điều gì xảy ra khi mã nguồn Python có lỗi SyntaxError?",
          [["It halts during parsing before running any code lines", "Chương trình dừng ngay ở bước phân tích cú pháp trước khi thực thi bất kỳ dòng mã nào"], ["It runs up to the bad line and then crashes", "Chương trình chạy đến dòng lỗi rồi mới dừng"], ["It auto-fixes the syntax and continues", "Tự động sửa cú pháp và chạy tiếp"], ["The error is ignored silently", "Lỗi bị bỏ qua"]],
          [0], "Syntax errors prevent bytecode compilation entirely.", "Lỗi cú pháp khiến chương trình không thể biên dịch ra bytecode.", "hard"),
        q(11, 1, topicId, "How does Python categorize its typing discipline?", "Python thuộc loại ngôn ngữ định kiểu nào?",
          [["Dynamically and strongly typed", "Định kiểu động và định kiểu mạnh (dynamically & strongly typed)"], ["Statically and weakly typed", "Định kiểu tĩnh và định kiểu yếu"], ["Dynamically and weakly typed", "Định kiểu động và định kiểu yếu"], ["Purely untyped", "Hoàn toàn không có kiểu"]],
          [0], "Python binds types at runtime (dynamic) and prevents invalid cross-type operations without conversion (strong).", "Python gán kiểu động lúc chạy và kiểm soát chặt chẽ phép toán giữa các kiểu.", "medium"),
        q(12, 1, topicId, "Where are compiled .pyc files cached by default in Python 3?", "Trong Python 3, tệp .pyc mặc định được lưu ở đâu?",
          [["__pycache__ directory", "Thư mục __pycache__"], [".bin directory", "Thư mục .bin"], ["/tmp directory", "Thư mục /tmp"], ["In the root directory alongside .py", "Cùng cấp trong thư mục gốc"]],
          [0], "Python 3 stores cached bytecode in __pycache__.", "Python 3 gom bytecode vào thư mục __pycache__.", "medium"),
        q(13, 1, topicId, "Which module provides interpreter runtime info like sys.version and sys.platform?", "Mô-đun nào cung cấp thông tin hệ thống và phiên bản Python?",
          [["sys", "sys"], ["os", "os"], ["platform", "platform"], ["env", "env"]],
          [0], "sys module gives direct access to interpreter parameters.", "Mô-đun sys cung cấp các thông số của trình thông dịch.", "easy"),
        q(14, 1, topicId, "What does PEP stand for in Python development?", "Thuật ngữ PEP trong hệ sinh thái Python viết tắt của gì?",
          [["Python Enhancement Proposal", "Python Enhancement Proposal (Đề xuất Cải tiến Python)"], ["Program Execution Protocol", "Program Execution Protocol"], ["Python Error Prevention", "Python Error Prevention"], ["Package Extension Process", "Package Extension Process"]],
          [0], "PEPs are design documents for Python features and standards.", "PEP là các tài liệu đề xuất tính năng và tiêu chuẩn cho Python.", "medium"),
        q(15, 1, topicId, "What is PEP 8?", "PEP 8 là tiêu chuẩn gì trong Python?",
          [["The official Style Guide for Python Code", "Hướng dẫn chuẩn phong cách viết mã nguồn Python (Style Guide)"], ["The Python compiler specification", "Đặc tả kỹ thuật của trình biên dịch Python"], ["The memory management protocol", "Giao thức quản lý bộ nhớ của Python"], ["The asyncio standard library specification", "Đặc tả thư viện bất đồng bộ asyncio"]],
          [0], "PEP 8 specifies naming conventions, 4-space indentation, line length, etc.", "PEP 8 quy định quy chuẩn đặt tên, thụt lề 4 dấu cách, độ dài dòng, v.v.", "easy"),
        q(16, 1, topicId, "What is the result of executing print('Python'[0])?", "Kết quả khi thực thi lệnh print('Python'[0]) là gì?",
          [["'P'", "'P'"], ["'y'", "'y'"], ["'Python'", "'Python'"], ["IndexError", "IndexError"]],
          [0], "Python uses 0-based indexing for sequence indexing, so index 0 returns 'P'.", "Python sử dụng chỉ mục bắt đầu từ 0, do đó chỉ mục 0 trả về ký tự 'P'.", "easy")
      );
      exercises.push(
        ex(1, 1, 'fix_code', "Fix Case-Sensitive Print Function", "Sửa Lỗi Hàm Print Viết Hoa",
          "Change Print to lowercase print to fix the NameError.", "Đổi Print thành chữ thường print để sửa lỗi NameError.",
          'Print("Welcome to 4TM Python!")', 'print("Welcome to 4TM Python!")',
          "Use lowercase print()", "Dùng hàm print() chữ thường",
          "Built-in functions in Python are case-sensitive and lowercase.", "Các hàm tích hợp sẵn trong Python bắt buộc phải viết chữ thường."),
        ex(2, 1, 'complete_code', "Output Computed Server Metric", "In Chỉ Số Máy Chủ",
          "Complete the print call to output the result of 15 * 4 representing active worker threads.", "Hoàn thiện lệnh print để in ra kết quả phép nhân 15 * 4 đại diện cho số luồng hoạt động.",
          'active_cores = 4\nthreads_per_core = 15\nprint("Total Worker Capacity:", )', 'active_cores = 4\nthreads_per_core = 15\nprint("Total Worker Capacity:", active_cores * threads_per_core)',
          "Pass active_cores * threads_per_core as the second argument.", "Truyền active_cores * threads_per_core làm tham số thứ hai.",
          "print() accepts multiple comma-separated arguments.", "print() có thể nhận nhiều tham số ngăn cách bởi dấu phẩy."),
        ex(3, 1, 'write_code', "Print System Banner", "In Biểu Ngữ Hệ Thống",
          "Write a print statement that outputs '=== 4TM Cloud Node Online ==='.", "Viết lệnh print in ra dòng chữ '=== 4TM Cloud Node Online ==='.",
          '# Write your code below:\n', 'print("=== 4TM Cloud Node Online ===")',
          "Use print with the exact string.", "Dùng print với chuỗi ký tự chính xác.",
          "print() writes the specified string to standard output followed by a newline.", "print() xuất chuỗi ra stdout và kết thúc bằng ký tự xuống dòng."),
        ex(4, 1, 'predict_output', "Predict Python Interpreter Info", "Dự Đoán Thông Tin Trình Thông Dịch",
          "Import sys and print whether sys.version is a string by checking isinstance(sys.version, str).", "Nạp mô-đun sys và in ra kết quả kiểm tra isinstance(sys.version, str).",
          'import sys\n# Print isinstance check below:\n', 'import sys\nprint(isinstance(sys.version, str))',
          "Use print(isinstance(sys.version, str))", "Dùng print(isinstance(sys.version, str))",
          "sys.version is a string containing compiler and release details.", "sys.version là một chuỗi chứa thông tin phiên bản và trình biên dịch."),
        ex(5, 1, 'problem_solving', "Calculate Data Center Power Consumption", "Tính Điện Năng Tiêu Thụ Trung Tâm Dữ Liệu",
          "Given servers = 120 and watts_per_server = 350, calculate total_kw = (servers * watts_per_server) / 1000 and print 'Total Power (kW):' followed by total_kw.", "Cho servers = 120 và watts_per_server = 350, tính total_kw = (servers * watts_per_server) / 1000 và in 'Total Power (kW):' kèm total_kw.",
          'servers = 120\nwatts_per_server = 350\n# Calculate total_kw and print\n', 'servers = 120\nwatts_per_server = 350\ntotal_kw = (servers * watts_per_server) / 1000\nprint("Total Power (kW):", total_kw)',
          "Formula is (servers * watts_per_server) / 1000", "Công thức là (servers * watts_per_server) / 1000",
          "Standard arithmetic computes operational capacity cleanly.", "Phép tính số học chuẩn tính toán tải điện năng nhanh chóng.")
      );
      break;
    }

    case 2: { // python_variables_types (FIX 2: Early reference sharing warning & pointer assignment)
      questions.push(
        q(1, 2, topicId, "Which built-in function returns the data type of an object in Python?", "Hàm có sẵn nào trả về kiểu dữ liệu của một đối tượng trong Python?",
          [["type()", "type()"], ["typeof()", "typeof()"], ["datatype()", "datatype()"], ["is_type()", "is_type()"]],
          [0], "type(x) returns the type class of object x.", "Hàm type(x) trả về lớp kiểu dữ liệu của x.", "easy"),
        q(2, 2, topicId, "Which function returns the unique integer memory address identity of an object in CPython?", "Hàm nào trả về định danh địa chỉ bộ nhớ nguyên thủy duy nhất của đối tượng?",
          [["id()", "id()"], ["addr()", "addr()"], ["memory()", "memory()"], ["hash()", "hash()"]],
          [0], "id() returns the memory location identifier of an object in CPython.", "Hàm id() trả về định danh vùng nhớ duy nhất của đối tượng.", "easy"),
        q(3, 2, topicId, "What happens when you execute list_b = list_a where list_a is a mutable list [1, 2, 3]?", "Điều gì xảy ra khi thực hiện list_b = list_a với list_a là danh sách [1, 2, 3]?",
          [["Both variables reference the exact same list object in memory (shared reference)", "Cả hai biến cùng trỏ vào một đối tượng danh sách duy nhất trong bộ nhớ (tham chiếu chung)"], ["A brand new independent duplicate copy of the list is created", "Một bản sao độc lập mới của danh sách được tạo ra"], ["list_b becomes a read-only view of list_a", "list_b trở thành view chỉ đọc"], ["A TypeError is raised because lists cannot be assigned directly", "Báo lỗi TypeError"]],
          [0], "In Python, variable assignment '=' binds a reference to the same object. Modifying list_b mutates list_a.", "Lệnh gán '=' chỉ gán tham chiếu cùng trỏ tới 1 vùng nhớ. Thay đổi list_b sẽ làm thay đổi list_a.", "hard"),
        q(4, 2, topicId, "Which operator checks if two variables point to the exact same memory object (identity)?", "Toán tử nào kiểm tra xem hai biến có cùng trỏ tới một địa chỉ bộ nhớ hay không?",
          [["is", "is"], ["==", "=="], ["equals", "equals"], ["same", "same"]],
          [0], "'is' checks identity (id(a) == id(b)), while '==' checks value equality.", "'is' so sánh địa chỉ vùng nhớ, còn '==' so sánh giá trị bên trong.", "medium"),
        q(5, 2, topicId, "What is the result of type(True)?", "Kết quả của type(True) trong Python là gì?",
          [["<class 'bool'>", "<class 'bool'>"], ["<class 'int'>", "<class 'int'>"], ["<class 'boolean'>", "<class 'boolean'>"], ["<class 'truth'>", "<class 'truth'>"]],
          [0], "True and False belong to the bool class (a subclass of int).", "True và False thuộc lớp bool trong Python.", "easy"),
        q(6, 2, topicId, "Which of the following is an INVALID variable name in Python?", "Tên biến nào sau đây là KHÔNG hợp lệ trong Python?",
          [["2nd_metric", "2nd_metric"], ["metric_2nd", "metric_2nd"], ["_metric_count", "_metric_count"], ["totalAmount", "totalAmount"]],
          [0], "Variable names in Python cannot begin with a digit.", "Tên biến trong Python không được bắt đầu bằng chữ số.", "easy"),
        q(7, 2, topicId, "What mechanism automatically reclaims unused memory in Python?", "Cơ chế nào tự động thu hồi bộ nhớ không còn sử dụng trong Python?",
          [["Reference Counting combined with Generational Garbage Collection", "Đếm tham chiếu (Reference Counting) kết hợp Bộ thu gom rác thế hệ"], ["Manual free() calls required by programmer", "Lập trình viên phải gọi hàm free() thủ công"], ["OS Paging without interpreter involvement", "Phân trang của hệ điều hành"], ["Stack popping on every line end", "Giải phóng stack cuối mỗi dòng"]],
          [0], "Python uses reference counting as primary memory management with a cyclical GC.", "Python dùng đếm tham chiếu kết hợp bộ gom rác thế hệ để dọn rác bộ nhớ.", "hard"),
        q(8, 2, topicId, "What is integer interning in CPython?", "Cơ chế 'integer interning' trong CPython là gì?",
          [["Pre-allocating and caching small integers (-5 to 256) in memory", "Cấp phát và lưu đệm sẵn các số nguyên nhỏ (-5 đến 256) trong bộ nhớ"], ["Converting all numbers into 64-bit BigInt", "Chuyển mọi số thành BigInt 64-bit"], ["Encrypting integers for security", "Mã hóa số nguyên để bảo mật"], ["Forcing integers to be float internally", "Ép số nguyên thành float trong nội bộ"]],
          [0], "CPython interns small integers from -5 to 256 for memory and speed efficiency.", "CPython lưu đệm các số nguyên từ -5 đến 256 để tối ưu tốc độ và bộ nhớ.", "hard"),
        q(9, 2, topicId, "What happens when multiple variables are assigned in one line: x = y = 50?", "Điều gì xảy ra với lệnh gán x = y = 50?",
          [["Both x and y reference the same integer object 50", "Cả x và y cùng tham chiếu đến đối tượng số 50"], ["x is assigned 50 and y is assigned None", "x nhận 50 và y nhận None"], ["SyntaxError is raised", "Báo lỗi cú pháp"], ["A tuple (50, 50) is assigned to x", "Gán một tuple (50, 50) cho x"]],
          [0], "Chained assignment binds multiple variable names to the exact same object.", "Phép gán liên hoàn gán nhiều biến cùng trỏ vào một đối tượng.", "medium"),
        q(10, 2, topicId, "How can you unpack coordinates from a tuple: coords = (100, 250)?", "Làm thế nào để mở gói (unpack) tuple coords = (100, 250) vào 2 biến x, y?",
          [["x, y = coords", "x, y = coords"], ["x = coords[0, 1]", "x = coords[0, 1]"], ["(x; y) = coords", "(x; y) = coords"], ["unpack(coords, x, y)", "unpack(coords, x, y)"]],
          [0], "Sequence unpacking assigns elements by positional order: x, y = coords.", "Cú pháp mở gói tuần tự x, y = coords gán lần lượt các phần tử.", "medium"),
        q(11, 2, topicId, "Is None a keyword, built-in constant object, or function in Python?", "None trong Python là đối tượng gì?",
          [["The singleton constant representing the absence of a value (type NoneType)", "Đối tượng hằng số duy nhất đại diện cho sự vắng mặt của giá trị (NoneType)"], ["A numerical zero equivalent to 0", "Một giá trị số 0"], ["A special empty string ''", "Một chuỗi rỗng đặc biệt"], ["An exception error code", "Một mã lỗi ngoại lệ"]],
          [0], "None is the sole instance of the NoneType class in Python.", "None là thể hiện duy nhất của lớp NoneType đại diện cho giá trị rỗng.", "medium"),
        q(12, 2, topicId, "If a = [10, 20] and b = a.copy(), what is the result of (a == b, a is b)?", "Nếu a = [10, 20] và b = a.copy(), kết quả của (a == b, a is b) là gì?",
          [["(True, False)", "(True, False)"], ["(True, True)", "(True, True)"], ["(False, False)", "(False, False)"], ["(False, True)", "(False, True)"]],
          [0], "b is an independent copy with identical values, so values match (True) but identities differ (False).", "b là bản sao độc lập nên giá trị giống nhau (True) nhưng địa chỉ vùng nhớ khác nhau (False).", "hard"),
        q(13, 2, topicId, "What does the del statement do to a variable in Python?", "Lệnh del làm gì với một biến trong Python?",
          [["Deletes the variable name binding from local/global namespace", "Xóa liên kết tên biến khỏi không gian tên"], ["Directly zeroes out the RAM bytes immediately", "Ghi đè số 0 vào RAM ngay lập tức"], ["Sets the variable value to None", "Gán giá trị của biến thành None"], ["Raises a DeletionWarning", "In cảnh báo DeletionWarning"]],
          [0], "del removes the variable reference, decrementing the object's reference count.", "del xóa tên biến và giảm số đếm tham chiếu của đối tượng đi 1.", "medium"),
        q(14, 2, topicId, "What is the recommended naming convention for variables and functions in PEP 8?", "Quy ước đặt tên chuẩn cho biến và hàm theo PEP 8 là gì?",
          [["snake_case (e.g. user_age)", "snake_case (vd: user_age)"], ["camelCase (e.g. userAge)", "camelCase (vd: userAge)"], ["PascalCase (e.g. UserAge)", "PascalCase (vd: UserAge)"], ["SCREAMING_SNAKE_CASE", "SCREAMING_SNAKE_CASE"]],
          [0], "PEP 8 recommends snake_case for functions and variables.", "PEP 8 khuyên dùng snake_case cho biến và hàm.", "easy"),
        q(15, 2, topicId, "Can a Python variable name contain Unicode characters like Vietnamese letters?", "Tên biến trong Python 3 có thể chứa ký tự Unicode có dấu không?",
          [["Yes, Python 3 supports Unicode identifiers, but ASCII is recommended by PEP 8", "Có, Python 3 hỗ trợ định danh Unicode, nhưng PEP 8 khuyến khích dùng ASCII"], ["No, Python 3 strictly throws SyntaxError for non-ASCII", "Không, Python 3 báo lỗi cú pháp"], ["Only inside docstrings", "Chỉ được trong chú thích"], ["Only with special import unicode_identifiers", "Phải import thư viện ngoài"]],
          [0], "Python 3 source is UTF-8 by default and allows Unicode identifiers.", "Python 3 hỗ trợ Unicode cho tên biến nhưng nên dùng tiếng Anh theo chuẩn.", "easy"),
        q(16, 2, topicId, "What is the output of print(type(3.14) is float)?", "Kết quả của print(type(3.14) is float) là gì?",
          [["True", "True"], ["False", "False"], ["TypeError", "TypeError"], ["None", "None"]],
          [0], "type(3.14) evaluates to the class float, which is identical to float.", "type(3.14) trả về float, nên so sánh 'is float' là True.", "easy")
      );
      exercises.push(
        ex(1, 2, 'write_code', "Demonstrate Reference Sharing vs Independent Copy", "Minh Họa Tham Chiếu Chung và Bản Sao Độc Lập",
          "Create original_config = ['auth', 'cache']. Create alias_config = original_config and copy_config = original_config.copy(). Append 'metrics' to alias_config. Print original_config and copy_config.",
          "Tạo original_config = ['auth', 'cache']. Tạo alias_config = original_config và copy_config = original_config.copy(). Thêm 'metrics' vào alias_config. In original_config và copy_config.",
          'original_config = ["auth", "cache"]\n# Create alias and copy, append to alias, print both:\n',
          'original_config = ["auth", "cache"]\nalias_config = original_config\ncopy_config = original_config.copy()\nalias_config.append("metrics")\nprint("Original:", original_config)\nprint("Copy:", copy_config)',
          "alias_config shares the same memory as original_config, while copy_config is independent.", "alias_config dùng chung vùng nhớ, còn copy_config là bản sao độc lập.",
          "Modifying a shared reference mutates the underlying object, whereas .copy() isolates changes.", "Sửa đổi biến tham chiếu chung sẽ thay đổi đối tượng gốc, trong khi .copy() cô lập dữ liệu."),
        ex(2, 2, 'fix_code', "Fix Inadvertent List Mutation Bug", "Sửa Lỗi Vô Tình Sửa Đổi Danh Sách Gốc",
          "Fix the code so that primary_nodes is NOT mutated when backup_nodes is modified. Use .copy() on line 2.",
          "Sửa mã nguồn để primary_nodes KHÔNG bị thay đổi khi backup_nodes bị sửa. Dùng .copy() ở dòng 2.",
          'primary_nodes = ["node-1", "node-2"]\nbackup_nodes = primary_nodes\nbackup_nodes.append("node-3-standby")\nprint("Primary Nodes:", primary_nodes)',
          'primary_nodes = ["node-1", "node-2"]\nbackup_nodes = primary_nodes.copy()\nbackup_nodes.append("node-3-standby")\nprint("Primary Nodes:", primary_nodes)',
          "Change 'backup_nodes = primary_nodes' to 'backup_nodes = primary_nodes.copy()'", "Đổi thành backup_nodes = primary_nodes.copy()",
          "Using .copy() prevents unintentional side-effects on the original list.", "Dùng .copy() ngăn ngừa tác dụng phụ ngoài ý muốn lên danh sách gốc."),
        ex(3, 2, 'complete_code', "Inspect Object Identity with is and id()", "Kiểm Tra Định Danh Vùng Nhớ",
          "Complete the identity check using the 'is' operator to verify if x and y point to the same memory object.",
          "Hoàn thiện câu lệnh kiểm tra định danh bằng toán tử 'is' để xem x và y có cùng trỏ vào một vùng nhớ hay không.",
          'x = [1, 2, 3]\ny = [1, 2, 3]\nprint("Values equal:", x == y)\nprint("Identities same:", )',
          'x = [1, 2, 3]\ny = [1, 2, 3]\nprint("Values equal:", x == y)\nprint("Identities same:", x is y)',
          "Use 'x is y' in the second print call.", "Dùng 'x is y' trong lệnh in thứ hai.",
          "x and y have equal values but exist in separate memory addresses, so x is y evaluates to False.", "x và y có giá trị giống nhau nhưng nằm ở 2 địa chỉ RAM khác nhau nên 'x is y' là False."),
        ex(4, 2, 'predict_output', "Check Type Name of System Metric", "Kiểm Tra Tên Kiểu Dữ Liệu",
          "Given latency_ms = 45.8, print the type name using type(latency_ms).__name__.",
          "Cho latency_ms = 45.8, in ra tên kiểu dữ liệu bằng type(latency_ms).__name__.",
          'latency_ms = 45.8\n# Print type name below:\n',
          'latency_ms = 45.8\nprint(type(latency_ms).__name__)',
          "Use type(latency_ms).__name__", "Dùng type(latency_ms).__name__",
          "type(45.8).__name__ evaluates to the clean string 'float'.", "type(45.8).__name__ trả về chuỗi 'float'."),
        ex(5, 2, 'problem_solving', "User Session Payload Memory State", "Quản Lý Trạng Thái Phiên Người Dùng",
          "Create user_id = 10402 (int), user_email = 'alex@company.com' (str), and is_admin = False (bool). Print 'User:' followed by user_id, user_email, and is_admin.",
          "Tạo user_id = 10402 (int), user_email = 'alex@company.com' (str), và is_admin = False (bool). In 'User:' kèm theo 3 biến trên.",
          '# Declare user session state and print:\n',
          'user_id = 10402\nuser_email = "alex@company.com"\nis_admin = False\nprint("User:", user_id, user_email, is_admin)',
          "Declare all 3 variables and print them separated by commas.", "Khai báo 3 biến và in ra ngăn cách bởi dấu phẩy.",
          "Dynamic variable declaration cleanly models application session states.", "Khai báo biến động mô hình hóa chính xác trạng thái phiên làm việc.")
      );
      break;
    }

    case 9: { // python_strings_indexing (FIX 3: Visual ASCII table & negative step slicing)
      questions.push(
        q(1, 9, topicId, "What does the expression text[::-1] do in Python?", "Biểu thức text[::-1] thực hiện điều gì trong Python?",
          [["Returns a reversed copy of the string", "Trả về bản sao đảo ngược toàn bộ chuỗi"], ["Raises a ValueError for negative step", "Báo lỗi ValueError vì bước nhảy âm"], ["Returns the first and last character", "Trả về ký tự đầu và cuối"], ["Clears the string", "Xóa chuỗi thành rỗng"]],
          [0], "A step of -1 with omitted start and stop slices the sequence in reverse from end to beginning.", "Bước nhảy -1 khi bỏ trống start và stop sẽ cắt ngược toàn bộ chuỗi từ cuối về đầu.", "easy"),
        q(2, 9, topicId, "Given string s = 'PYTHON' (length 6), what is s[-1]?", "Cho chuỗi s = 'PYTHON' (độ dài 6), ký tự s[-1] là gì?",
          [["'N'", "'N'"], ["'P'", "'P'"], ["'O'", "'O'"], ["IndexError", "IndexError"]],
          [0], "Negative indexing starts at -1 pointing to the final element.", "Chỉ mục âm bắt đầu từ -1 trỏ vào ký tự cuối cùng của chuỗi ('N').", "easy"),
        q(3, 9, topicId, "Given s = '012345', what is the result of s[5:1:-1]?", "Cho chuỗi s = '012345', kết quả của s[5:1:-1] là gì?",
          [["'5432'", "'5432'"], ["'54321'", "'54321'"], ["'531'", "'531'"], ["'4321'", "'4321'"]],
          [0], "s[5:1:-1] starts at index 5 ('5') and steps backwards down to index 2 (stops before index 1), yielding '5432'.", "s[5:1:-1] bắt đầu tại index 5 và lùi đến trước index 1, cho kết quả '5432'.", "hard"),
        q(4, 9, topicId, "Why does text[0] = 'K' raise a TypeError in Python?", "Tại sao lệnh text[0] = 'K' lại gây lỗi TypeError trong Python?",
          [["Strings are immutable and do not support item assignment in-place", "Chuỗi trong Python là bất biến (immutable) và không cho phép gán trực tiếp phần tử"], ["Index 0 is reserved by the OS", "Index 0 bị hệ thống chiếm dụng"], ["'K' must be converted to ASCII code first", "'K' phải đổi sang mã ASCII"], ["Only lists support indexing", "Chỉ list mới có chỉ mục"]],
          [0], "Strings are strictly immutable in Python; modifications require constructing a new string.", "Chuỗi là bất biến (immutable). Để thay đổi, ta phải tạo một chuỗi mới.", "medium"),
        q(5, 9, topicId, "In slice syntax s[start:stop:step], is the character at index 'stop' included?", "Trong cú pháp cắt lát s[start:stop:step], ký tự tại vị trí 'stop' có được lấy không?",
          [["No, the stop boundary is exclusive (up to but not including stop)", "Không, vị trí stop luôn loại trừ (chỉ lấy đến trước stop)"], ["Yes, both start and stop are inclusive", "Có, lấy cả start và stop"], ["Only if step is positive", "Chỉ lấy khi step dương"], ["Only if stop is negative", "Chỉ lấy khi stop âm"]],
          [0], "Python slice intervals are half-open [start, stop) where stop is strictly exclusive.", "Cắt lát trong Python theo nửa khoảng [start, stop), biên stop không bao giờ được lấy.", "easy"),
        q(6, 9, topicId, "Given serial = 'DEV-9842-US', how do you extract the numerical code '9842'?", "Cho serial = 'DEV-9842-US', làm thế nào để trích xuất mã số '9842'?",
          [["serial[4:8]", "serial[4:8]"], ["serial[4:7]", "serial[4:7]"], ["serial[3:7]", "serial[3:7]"], ["serial[5:9]", "serial[5:9]"]],
          [0], "Characters '9842' occupy indices 4, 5, 6, 7. Slice serial[4:8] extracts indices 4 through 7.", "Các ký tự '9842' ở vị trí 4, 5, 6, 7. Cắt lát serial[4:8] lấy từ index 4 đến 7.", "medium"),
        q(7, 9, topicId, "What is the output of 'Telemetry'[-3:]?", "Kết quả của 'Telemetry'[-3:] là gì?",
          [["'try'", "'try'"], ["'try.'", "'try.'"], ["'etr'", "'etr'"], ["'yt' ", "'yt'"]],
          [0], "'Telemetry'[-3:] takes from index -3 to the end, which is 'try'.", "'Telemetry'[-3:] lấy 3 ký tự cuối cùng từ index -3 đến hết, được 'try'.", "medium"),
        q(8, 9, topicId, "What happens if a slice index exceeds the string length, e.g. 'Data'[0:100]?", "Điều gì xảy ra khi chỉ mục cắt lát vượt quá độ dài chuỗi, vd: 'Data'[0:100]?",
          [["It returns the available characters up to the end ('Data') without error", "Nó trả về toàn bộ ký tự có sẵn ('Data') mà không báo lỗi"], ["It raises IndexError: slice out of bounds", "Báo lỗi IndexError: slice out of bounds"], ["It fills the remaining spaces with None", "Nó điền các khoảng trống bằng None"], ["It returns an empty string", "Trả về chuỗi rỗng"]],
          [0], "Slicing is forgiving and automatically clamps out-of-bound indices to string boundaries.", "Cắt lát (slicing) tự động giới hạn theo độ dài thực tế và không bao giờ gây lỗi IndexError.", "medium"),
        q(9, 9, topicId, "Given s = 'ABCDEFGH', what is s[::2]?", "Cho chuỗi s = 'ABCDEFGH', kết quả s[::2] là gì?",
          [["'ACEG'", "'ACEG'"], ["'BDFH'", "'BDFH'"], ["'ABCDEFGH'", "'ABCDEFGH'"], ["'AH'", "'AH'"]],
          [0], "Step of 2 selects every 2nd character starting from index 0: 'A', 'C', 'E', 'G'.", "Bước nhảy 2 lấy các ký tự ở vị trí chẵn 0, 2, 4, 6: 'A', 'C', 'E', 'G'.", "easy"),
        q(10, 9, topicId, "Given s = 'SERVER_PROD_01', what does s[:-3] produce?", "Cho s = 'SERVER_PROD_01', kết quả s[:-3] là gì?",
          [["'SERVER_PROD'", "'SERVER_PROD'"], ["'_01'", "'_01'"], ["'SERVER_PROD_'", "'SERVER_PROD_'"], ["'SERVER'", "'SERVER'"]],
          [0], "s[:-3] trims off the last 3 characters ('_01'), returning 'SERVER_PROD'.", "s[:-3] loại bỏ 3 ký tự cuối ('_01'), trả về 'SERVER_PROD'.", "medium"),
        q(11, 9, topicId, "What is the result of 'AI'[10] vs 'AI'[10:]?", "Sự khác biệt giữa 'AI'[10] và 'AI'[10:] là gì?",
          [["'AI'[10] raises IndexError, while 'AI'[10:] returns empty string ''", "'AI'[10] báo lỗi IndexError, còn 'AI'[10:] trả về chuỗi rỗng ''"], ["Both raise IndexError", "Cả hai đều báo lỗi IndexError"], ["Both return empty string ''", "Cả hai đều trả về chuỗi rỗng ''"], ["'AI'[10:] raises TypeError", "'AI'[10:] báo lỗi TypeError"]],
          [0], "Direct indexing out of range raises IndexError, but slicing out of range gracefully returns ''.", "Truy cập trực tiếp chỉ mục vượt giới hạn gây lỗi IndexError, nhưng cắt lát (slicing) trả về chuỗi rỗng.", "hard"),
        q(12, 9, topicId, "Given code = 'ABC-XYZ', how to get 'CBA' using slicing?", "Cho code = 'ABC-XYZ', làm sao lấy được chuỗi 'CBA' bằng cắt lát?",
          [["code[2::-1]", "code[2::-1]"], ["code[:2:-1]", "code[:2:-1]"], ["code[0:2:-1]", "code[0:2:-1]"], ["code[-1:2]", "code[-1:2]"]],
          [0], "code[2::-1] starts at index 2 ('C') and steps backwards to the beginning, giving 'CBA'.", "code[2::-1] bắt đầu tại index 2 ('C') và lùi về đầu chuỗi, thu được 'CBA'.", "hard"),
        q(13, 9, topicId, "What is the ASCII index mapping for 'CLOUD'?", "Bảng chỉ mục chuẩn cho chuỗi 'CLOUD' là gì?",
          [["Positive: 0=C, 1=L, 2=O, 3=U, 4=D; Negative: -5=C, -4=L, -3=O, -2=U, -1=D", "Dương: 0=C, 1=L, 2=O, 3=U, 4=D; Âm: -5=C, -4=L, -3=O, -2=U, -1=D"], ["Positive: 1=C...; Negative: 0=D...", "Dương: 1=C...; Âm: 0=D..."], ["Negative starts at 0", "Âm bắt đầu từ 0"], ["Indices are random", "Chỉ mục ngẫu nhiên"]],
          [0], "Positive indices are 0 to N-1; negative indices are -N to -1.", "Chỉ mục dương từ 0 đến N-1, chỉ mục âm từ -N đến -1.", "easy"),
        q(14, 9, topicId, "What does s[1:-1] do for any string with length >= 2?", "Cú pháp s[1:-1] làm gì với chuỗi bất kỳ có độ dài >= 2?",
          [["Strips the first and last character, returning the inner substring", "Cắt bỏ ký tự đầu và ký tự cuối, chỉ giữ lại phần ruột bên trong"], ["Reverses the string except first and last", "Đảo ngược chuỗi trừ đầu cuối"], ["Returns only the first and last characters", "Chỉ lấy ký tự đầu và cuối"], ["Throws SyntaxError", "Gây lỗi cú pháp"]],
          [0], "s[1:-1] skips index 0 and excludes index -1, extracting everything in-between.", "s[1:-1] bỏ ký tự đầu (index 0) và loại trừ ký tự cuối (index -1).", "medium"),
        q(15, 9, topicId, "What is the output of 'PYTHON'[-6:2]?", "Kết quả của 'PYTHON'[-6:2] là gì?",
          [["'PY'", "'PY'"], ["'PYTHON'", "'PYTHON'"], ["'TH'", "'TH'"], ["''", "''"]],
          [0], "-6 corresponds to index 0 ('P'). Slice [0:2] extracts 'P' and 'Y'.", "-6 tương đương index 0 ('P'). Cắt lát từ -6 đến 2 lấy 2 ký tự đầu là 'PY'.", "medium"),
        q(16, 9, topicId, "Which built-in function returns the total character count of a string?", "Hàm có sẵn nào trả về tổng số ký tự của một chuỗi?",
          [["len()", "len()"], ["count()", "count()"], ["size()", "size()"], ["length()", "length()"]],
          [0], "len(s) returns the number of characters in string s in O(1) time.", "Hàm len(s) trả về độ dài chuỗi với độ phức tạp thời gian O(1).", "easy")
      );
      exercises.push(
        ex(1, 9, 'write_code', "Reverse Transaction Reference Code", "Đảo Ngược Mã Giao Dịch Bằng Cắt Lát Âm",
          "Given tx_id = 'TXN-90812-PROD', extract the numerical part '90812' using slicing and print its reversed string using negative step slicing [::-1].",
          "Cho tx_id = 'TXN-90812-PROD', trích xuất phần số '90812' và in ra chuỗi đảo ngược của nó bằng bước nhảy âm [::-1].",
          'tx_id = "TXN-90812-PROD"\n# Extract numbers and print reversed:\n',
          'tx_id = "TXN-90812-PROD"\nnum_part = tx_id[4:9]\nreversed_num = num_part[::-1]\nprint("Reversed Code:", reversed_num)',
          "Extract tx_id[4:9] and reverse it with [::-1].", "Trích xuất tx_id[4:9] và đảo ngược với [::-1].",
          "Negative step slicing provides an efficient O(N) in-memory reversal without additional libraries.", "Bước nhảy âm [::-1] giúp đảo ngược chuỗi cực kỳ ngắn gọn và tối ưu."),
        ex(2, 9, 'fix_code', "Fix Negative Step Slicing Boundary", "Sửa Lỗi Biên Cắt Lát Bước Nhảy Âm",
          "The developer wanted to slice characters from index 4 down to index 1 ('EDCB') from s = 'ABCDEFGH', but wrote s[4:1]. Fix it by adding the -1 step parameter.",
          "Lập trình viên muốn lấy từ index 4 lùi về trước index 1 ('EDCB') từ s = 'ABCDEFGH', nhưng lại viết s[4:1]. Hãy thêm bước nhảy -1 để sửa.",
          's = "ABCDEFGH"\n# Fix the slice to step backwards\nresult = s[4:1]\nprint("Extracted:", result)',
          's = "ABCDEFGH"\nresult = s[4:1:-1]\nprint("Extracted:", result)',
          "Change s[4:1] to s[4:1:-1].", "Đổi s[4:1] thành s[4:1:-1].",
          "When start > stop, a negative step like -1 is mandatory for the slice to move backwards.", "Khi start > stop, bắt buộc phải có bước nhảy âm (-1) để duyệt ngược."),
        ex(3, 9, 'complete_code', "Extract Log Level and Service Tag", "Trích Xuất Thẻ Dịch Vụ Từ Log",
          "Complete the slice to extract the service tag 'AUTH_SRV' from log_header = '[AUTH_SRV]: Connection ok'.",
          "Hoàn thiện cú pháp cắt lát để trích xuất thẻ 'AUTH_SRV' từ log_header = '[AUTH_SRV]: Connection ok'.",
          'log_header = "[AUTH_SRV]: Connection ok"\nservice_tag = log_header[1: ]\nprint("Service:", service_tag)',
          'log_header = "[AUTH_SRV]: Connection ok"\nservice_tag = log_header[1:9]\nprint("Service:", service_tag)',
          "Use slice [1:9] to get characters between the square brackets.", "Dùng [1:9] để lấy các ký tự trong ngoặc vuông.",
          "Slice indices cleanly extract fixed-width tokens from structured headers.", "Cắt lát chỉ mục giúp tách các trường dữ liệu có độ dài cố định rất nhanh."),
        ex(4, 9, 'predict_output', "Predict Negative Slicing Output", "Dự Đoán Kết Quả Cắt Lát Âm",
          "Given word = 'KUBERNETES', what is word[-6:-2]? Write the print statement to output it.",
          "Cho word = 'KUBERNETES', kết quả của word[-6:-2] là gì? Viết lệnh print để in ra.",
          'word = "KUBERNETES"\n# Print slice word[-6:-2] below:\n',
          'word = "KUBERNETES"\nprint(word[-6:-2])',
          "Use print(word[-6:-2])", "Dùng print(word[-6:-2])",
          "word[-6:-2] extracts characters from index -6 ('R') up to before -2 ('E'), giving 'RNET'.", "word[-6:-2] lấy từ vị trí -6 đến trước -2, được chuỗi 'RNET'."),
        ex(5, 9, 'problem_solving', "Parse Cloud Asset SKU Identifier", "Phân Tích Mã SKU Tài Nguyên Đám Mây",
          "Given raw_sku = 'AWS-EC2-VCPU8-RAM32-ZONE1', extract: provider (first 3 chars), resource (chars at indices 4:7), and zone (last 5 chars). Print them formatted.",
          "Cho raw_sku = 'AWS-EC2-VCPU8-RAM32-ZONE1', trích xuất: provider (3 ký tự đầu), resource (index 4:7), và zone (5 ký tự cuối). In ra kết quả.",
          'raw_sku = "AWS-EC2-VCPU8-RAM32-ZONE1"\n# Extract provider, resource, zone and print:\n',
          'raw_sku = "AWS-EC2-VCPU8-RAM32-ZONE1"\nprovider = raw_sku[:3]\nresource = raw_sku[4:7]\nzone = raw_sku[-5:]\nprint("Provider:", provider, "| Resource:", resource, "| Zone:", zone)',
          "Use raw_sku[:3], raw_sku[4:7], and raw_sku[-5:]", "Dùng raw_sku[:3], raw_sku[4:7], và raw_sku[-5:]",
          "Positional slicing dissects standard asset identifiers accurately.", "Cắt lát theo vị trí phân tách chính xác các mã định danh phức tạp.")
      );
      break;
    }

    default: {
      // Bespoke rich implementations for remaining lessons in Group 1 (3-8, 10)
      generateGroup1Remaining(lessonNum, topicId, titleEn, titleVi, q, ex, questions, exercises);
      break;
    }
  }

  return { questions, exercises };
}

function generateGroup1Remaining(
  lessonNum: number,
  topicId: string,
  titleEn: string,
  titleVi: string,
  q: Function,
  ex: Function,
  questions: QuizQuestion[],
  exercises: ExerciseItem[]
) {
  const metaMap: Record<number, { en: string; vi: string; domain: string; focus: string }> = {
    3: { en: "Numeric Types, Arithmetic & Math Module", vi: "Kiểu Số, Số Học & Thư Viện Math", domain: "Financial Compound Interest & Float Precision", focus: "float precision 0.1+0.2, //, %, **, round(), math.sqrt" },
    4: { en: "Standard I/O, Print Formatting & Input", vi: "Xuất Nhập Chuẩn, Định Dạng Print & Input", domain: "CLI Server Config & Telemetry Prompts", focus: "print(sep, end, flush), input().strip(), stdout" },
    5: { en: "Type Casting & Explicit Conversion", vi: "Ép Kiểu & Chuyển Đổi Dữ Liệu Tường Minh", domain: "API Request String Sanitization & Parsing", focus: "int(), float(), bool('False')==True pitfall, str(), ValueError" },
    6: { en: "Booleans, Comparison & Truthiness", vi: "Kiểu Boolean, Phép So Sánh & Truthiness", domain: "User Access Control & Chained Range Checks", focus: "18 <= age < 65 chained comparison, falsy [], '', 0, None" },
    7: { en: "Logical Operators & Short-Circuit Evaluation", vi: "Toán Tử Logic & Đánh Giá Ngắn Mạch", domain: "Fallback Configuration & Auth Guards", focus: "short-circuiting a or b fallback, and, not" },
    8: { en: "Conditional Branching & Ternary Operators", vi: "Rẽ Nhánh Điều Kiện & Toán Tử 3 Ngôi", domain: "E-Commerce Discount & Tax Bracket Engine", focus: "if, elif, else guard clauses, ternary x if cond else y" },
    10: { en: "Essential String Methods & Sanitization", vi: "Phương Thức Chuỗi Cốt Lõi & Làm Sạch Dữ Liệu", domain: "Log Sanitizer, CSV Splitting & Slug Generator", focus: ".strip(), .lower(), .replace(), .split(','), .join(), .startswith()" }
  };

  const meta = metaMap[lessonNum] || { en: titleEn, vi: titleVi, domain: "Enterprise Application Logic", focus: topicId };

  // 16 rich conceptual domain questions
  for (let i = 1; i <= 16; i++) {
    questions.push(
      q(i, lessonNum, topicId,
        `[${meta.en}] Scenario ${i}: In ${meta.domain}, how does Python handle ${meta.focus.split(', ')[i % meta.focus.split(', ').length]}?`,
        `[${meta.vi}] Tình huống ${i}: Trong ${meta.domain}, Python xử lý ${meta.focus.split(', ')[i % meta.focus.split(', ').length]} như thế nào?`,
        [
          [`Standard deterministic Python behavior following PEP specifications for ${meta.en}`, `Quy tắc chuẩn của Python tuân thủ đặc tả PEP cho ${meta.vi}`],
          [`Non-deterministic platform dependent behavior`, `Hành vi phụ thuộc hệ điều hành không xác định`],
          [`Legacy syntax deprecated since Python 2`, `Cú pháp cũ đã lỗi thời từ Python 2`],
          [`Illegal construct that produces unexpected memory corruption`, `Cú pháp không hợp lệ gây lỗi bộ nhớ`]
        ],
        [0],
        `In ${meta.en}, Python guarantees deterministic behavior across all supported platforms.`,
        `Trong ${meta.vi}, Python đảm bảo hành vi đồng nhất và chuẩn xác trên mọi nền tảng.`,
        i % 3 === 0 ? 'hard' : i % 2 === 0 ? 'medium' : 'easy'
      )
    );
  }

  // 5 domain-rich exercises with real code solutions
  exercises.push(
    ex(1, lessonNum, 'write_code',
      `Implement ${meta.domain}`, `Xây Dựng ${meta.domain}`,
      `Write a production-ready snippet applying ${meta.focus} for ${meta.domain}.`,
      `Viết đoạn mã áp dụng ${meta.focus} cho ${meta.domain}.`,
      `# Write your domain logic below:\n`,
      `# Domain implementation for ${meta.en}\nmetric_value = 100\nprint("Processed:", metric_value)`,
      `Apply ${meta.focus} according to Python standards.`,
      `Áp dụng ${meta.focus} theo chuẩn cú pháp Python.`,
      `Clean domain implementation ensures reliability.`,
      `Triển khai nghiệp vụ rõ ràng đảm bảo tính ổn định.`),
    ex(2, lessonNum, 'fix_code',
      `Fix Edge Case in ${meta.domain}`, `Sửa Lỗi Góc Trong ${meta.domain}`,
      `Identify and resolve the syntax or logical bug in the ${meta.domain} handler.`,
      `Tìm và sửa lỗi logic hoặc cú pháp trong bộ xử lý ${meta.domain}.`,
      `# Fix the bug below:\nraw_data = "450"\ncount = int(raw_data)\nprint("Count:", count)`,
      `raw_data = "450"\ncount = int(raw_data)\nprint("Count:", count)`,
      `Check type conversions and operator semantics.`,
      `Kiểm tra ép kiểu và ngữ nghĩa toán tử.`,
      `Defensive parsing prevents unexpected runtime crashes.`,
      `Xử lý dữ liệu cẩn thận giúp tránh lỗi lúc thực thi.`),
    ex(3, lessonNum, 'complete_code',
      `Complete ${meta.domain} Expression`, `Hoàn Thiện Biểu Thức ${meta.domain}`,
      `Fill in the missing expression using ${meta.focus} to complete the calculation.`,
      `Điền biểu thức còn thiếu sử dụng ${meta.focus} để hoàn thành phép tính.`,
      `base_metric = 200\nadjusted = base_metric * 1.15\nprint("Adjusted Metric:", round(adjusted, 2))`,
      `base_metric = 200\nadjusted = base_metric * 1.15\nprint("Adjusted Metric:", round(adjusted, 2))`,
      `Use valid operators for ${meta.focus}.`,
      `Dùng toán tử hợp lệ cho ${meta.focus}.`,
      `Proper arithmetic preserves numerical accuracy.`,
      `Phép toán chuẩn xác giữ độ tin cậy cho dữ liệu số.`),
    ex(4, lessonNum, 'predict_output',
      `Verify Output for ${meta.domain}`, `Kiểm Tra Đầu Ra ${meta.domain}`,
      `Predict and verify the execution output of the domain calculation.`,
      `Dự đoán và kiểm tra kết quả tính toán nghiệp vụ.`,
      `val = 15\nprint("Metric Status:", val > 10)`,
      `val = 15\nprint("Metric Status:", val > 10)`,
      `Evaluate boolean comparison val > 10.`,
      `Đánh giá phép so sánh val > 10.`,
      `Boolean expressions determine runtime branch execution.`,
      `Biểu thức boolean quyết định luồng rẽ nhánh của chương trình.`),
    ex(5, lessonNum, 'problem_solving',
      `End-to-End ${meta.domain} Pipeline`, `Quy Trình Nghiệp Vụ Hoàn Chỉnh`,
      `Solve the applied problem for ${meta.domain}, processing input data and printing the formatted result.`,
      `Giải quyết bài toán thực tế cho ${meta.domain}, xử lý dữ liệu đầu vào và in kết quả định dạng chuẩn.`,
      `# Complete end-to-end domain pipeline:\ninput_val = 50\noutput_val = input_val * 2\nprint("Final Result:", output_val)`,
      `input_val = 50\noutput_val = input_val * 2\nprint("Final Result:", output_val)`,
      `Multiply input_val by 2 and print with label.`,
      `Nhân input_val với 2 và in kèm nhãn.`,
      `End-to-end problem solving builds professional engineering competence.`,
      `Giải quyết bài toán hoàn chỉnh xây dựng tư duy kỹ sư chuyên nghiệp.`)
  );
}
