import { GlossaryEntry, ReferenceItem } from '../../types';

export const PYTHON_HANDBOOK_GLOSSARY: GlossaryEntry[] = [
  {
    term: 'Abstract Syntax Tree (AST)',
    definition: {
      en: 'A tree representation of the abstract syntactic structure of Python source code generated by the parser before bytecode compilation.',
      vi: 'Cây biểu diễn cấu trúc cú pháp trừu tượng của mã nguồn Python do parser sinh ra trước khi biên dịch sang bytecode.',
    },
    category: 'Architecture',
  },
  {
    term: 'Bytecode',
    definition: {
      en: 'The intermediate representation of Python programs executed by the CPython virtual machine and cached in `.pyc` files.',
      vi: 'Dạng biểu diễn mã trung gian của chương trình Python được máy ảo CPython thực thi và lưu đệm trong các file `.pyc`.',
    },
    category: 'Runtime',
  },
  {
    term: 'Closure',
    definition: {
      en: 'A function object that retains bindings to variables in its lexical enclosing scope via heap-allocated `__closure__` cell objects.',
      vi: 'Đối tượng hàm giữ lại liên kết với các biến trong phạm vi bao ngoài thông qua các đối tượng cell `__closure__` trên heap.',
    },
    category: 'Language Core',
  },
  {
    term: 'C3 Linearization',
    definition: {
      en: 'The algorithm used by Python 2.3+ to compute the unambiguous Method Resolution Order (MRO) in multiple inheritance class hierarchies.',
      vi: 'Thuật toán được Python sử dụng để tính toán thứ tự phân giải phương thức MRO nhất quán trong cây đa kế thừa.',
    },
    category: 'Object Model',
  },
  {
    term: 'Data Descriptor',
    definition: {
      en: 'A class attribute implementing `__set__` or `__delete__` (and optionally `__get__`), taking precedence over the instance `__dict__` during attribute lookup.',
      vi: 'Thuộc tính class có cài đặt `__set__` hoặc `__delete__`, có độ ưu tiên cao hơn `__dict__` của instance khi tra cứu thuộc tính.',
    },
    category: 'Metaprogramming',
  },
  {
    term: 'Global Interpreter Lock (GIL)',
    definition: {
      en: 'A mutex used by CPython to synchronize thread access to Python objects, preventing multiple threads from executing bytecode simultaneously.',
      vi: 'Khóa mutex trong CPython dùng để đồng bộ hóa truy cập của các luồng, ngăn không cho nhiều thread thực thi bytecode song song.',
    },
    category: 'Concurrency',
  },
  {
    term: 'Structural Subtyping (Protocol)',
    definition: {
      en: 'A type system paradigm where type compatibility and equivalence are determined by the shape/interface of the type (duck typing) rather than explicit inheritance.',
      vi: 'Mô hình hệ thống kiểu trong đó sự tương thích kiểu được xác định dựa trên hình thái/phương thức của đối tượng mà không cần kế thừa tường minh.',
    },
    category: 'Typing',
  },
];

export const PYTHON_HANDBOOK_REFERENCES: ReferenceItem[] = [
  {
    title: 'CPython Internal Source Code Repository',
    url: 'https://github.com/python/cpython',
    annotation: {
      en: 'The official C implementation of the Python virtual machine, parser, and standard library.',
      vi: 'Mã nguồn C chính thức của máy ảo Python, parser và thư viện chuẩn CPython.',
    },
  },
  {
    title: 'PEP 570 – Python Positional-Only Parameters',
    url: 'https://peps.python.org/pep-0570/',
    annotation: {
      en: 'Specification introducing the `/` syntax for positional-only argument enforcement in Python 3.8+.',
      vi: 'Đặc tả đưa cú pháp `/` vào Python 3.8+ để quy định tham số bắt buộc theo vị trí.',
    },
  },
  {
    title: 'PEP 544 – Protocols: Structural subtyping (static duck typing)',
    url: 'https://peps.python.org/pep-0544/',
    annotation: {
      en: 'Defines static duck typing and Protocol abstractions for Mypy, Pyright, and modern type checkers.',
      vi: 'Định nghĩa giao thức Duck Typing tĩnh cho các công cụ kiểm tra kiểu hiện đại.',
    },
  },
];

export const PYTHON_HANDBOOK_FURTHER_READING: ReferenceItem[] = [
  {
    title: 'Fluent Python (2nd Edition) by Luciano Ramalho',
    annotation: {
      en: 'The definitive deep guide to idiomatic Python, data model dunders, descriptors, and metaprogramming.',
      vi: 'Cuốn sách chuyên sâu kinh điển về Python chuẩn mực, Data Model, Descriptor và Metaprogramming.',
    },
  },
  {
    title: 'CPython Internals by Anthony Shaw',
    annotation: {
      en: 'A practical, step-by-step visual exploration of the CPython compiler, VM stack, and memory allocator.',
      vi: 'Khám phá chi tiết kiến trúc máy ảo CPython, stack VM và cơ chế cấp phát bộ nhớ.',
    },
  },
];
