import { Lesson } from '../../../../types';

export const lesson15: Lesson = {
  id: 'pbi_lesson_15',
  moduleId: 'pbi_mod_5',
  levelId: 'advanced',
  courseId: 'powerbi',
  order: 15,
  topicId: 'dax_advanced_table_functions',
  title: {
    en: 'Advanced Table Functions & Virtual Relationships: TREATAS, SUMMARIZE, ADDCOLUMNS, GENERATE',
    vi: 'Hàm Bảng Nâng Cao & Mối Quan Hệ Ảo: TREATAS, SUMMARIZE, ADDCOLUMNS, GENERATE'
  },
  summary: {
    en: 'Construct dynamic in-memory data structures, inject virtual relationships with TREATAS, and combine ADDCOLUMNS with SUMMARIZE safely.',
    vi: 'Xây dựng cấu trúc dữ liệu ảo trong bộ nhớ, tạo mối quan hệ ảo với TREATAS và kết hợp an toàn ADDCOLUMNS cùng SUMMARIZE.'
  },
  estimatedMinutes: 16,
  learn: {
    introduction: {
      en: 'DAX is not only a scalar calculation language; it is a full-featured relational table manipulation engine. Table functions return temporary in-memory tables that can be filtered, iterated, intersected, and used to inject virtual relationships without altering the physical model. TREATAS is the modern gold standard for establishing high-speed virtual filter propagation across disconnected tables.',
      vi: 'DAX không chỉ là ngôn ngữ tính toán số đơn lẻ; nó là một bộ máy xử lý bảng quan hệ hoàn chỉnh. Các hàm bảng trả về những bảng tạm thời trong bộ nhớ RAM có thể lọc, lặp duyệt, lấy giao và tạo ra các mối quan hệ ảo mà không cần sửa đổi sơ đồ vật lý. TREATAS là chuẩn mực vàng hiện đại để truyền bộ lọc ảo tốc độ cao giữa các bảng không có quan hệ vật lý.'
    },
    conceptExplanation: {
      en: 'Core Table Functions & Best Practice Patterns:\n1. TREATAS(TableExpression, TargetColumn1, [TargetColumn2], ...):\n   - Injects the column values of TableExpression as active filters onto the target model columns, establishing a virtual relationship at query time.\n2. ADDCOLUMNS & SUMMARIZE Best Practice:\n   - Never perform measure aggregations directly inside SUMMARIZE (causes clustering bugs).\n   - Always use the safe pattern: ADDCOLUMNS(SUMMARIZE(Table, GroupCol1, GroupCol2), "MeasureName", [Measure]).\n3. VALUES vs DISTINCT:\n   - VALUES includes the blank row generated by referential integrity violations; DISTINCT ignores it.\n4. GENERATE & CROSSJOIN:\n   - CROSSJOIN computes the full Cartesian product. GENERATE evaluates the second table expression for each row of the first table.',
      vi: 'Các hàm bảng cốt lõi và mẫu hình chuẩn mực:\n1. TREATAS(BiểuThứcBảng, CộtĐích1, [CộtĐích2], ...):\n   - Áp dụng các giá trị của BiểuThứcBảng làm bộ lọc trực tiếp lên các cột trong mô hình, tạo ra một mối quan hệ ảo tức thời tại thời điểm truy vấn.\n2. Mẫu hình chuẩn kết hợp ADDCOLUMNS & SUMMARIZE:\n   - Không bao giờ tính toán measure trực tiếp bên trong hàm SUMMARIZE (dễ gây lỗi phân nhóm sai dữ liệu).\n   - Luôn tuân thủ mẫu chuẩn an toàn: ADDCOLUMNS(SUMMARIZE(Bảng, CộtGomNhóm1, CộtGomNhóm2), "TênMeasure", [Measure]).\n3. VALUES so với DISTINCT:\n   - VALUES chứa dòng trống (blank row) sinh ra do lỗi toàn vẹn khóa ngoại; DISTINCT thì bỏ qua dòng trống đó.\n4. GENERATE và CROSSJOIN:\n   - CROSSJOIN tính tích Descartes toàn phần. GENERATE đánh giá biểu thức bảng thứ hai cho từng dòng của bảng thứ nhất.'
    },
    syntax: '// 1. Virtual Relationship with TREATAS:\nCALCULATE(\n    [Total Sales],\n    TREATAS(VALUES(BudgetTable[Category]), Dim_Products[Category])\n)\n\n// 2. Safe ADDCOLUMNS + SUMMARIZE pattern:\nVAR CustomerSalesTable = \n    ADDCOLUMNS(\n        SUMMARIZE(Sales, Dim_Customers[CustomerID], Dim_Customers[CustomerName]),\n        "CustomerRevenue", [Total Revenue]\n    )\nRETURN\n    AVERAGEX(CustomerSalesTable, [CustomerRevenue])',
    examples: [
      {
        title: {
          en: 'Comparing Actuals vs Budget with TREATAS Virtual Relationship',
          vi: 'So Sánh Thực Tế Với Ngân Sách Bằng Quan Hệ Ảo TREATAS'
        },
        code: `// Fact_Budget is aggregated at Month & Category level (different grain than Fact_Sales):
Actual Sales for Budgeted Categories = 
CALCULATE(
    [Total Sales],
    TREATAS(
        VALUES(Fact_Budget[CategoryName]),
        Dim_Products[Category]
    )
)`,
        language: 'dax',
        explanation: {
          en: 'TREATAS applies the active categories from the budget table as filters onto Dim_Products without needing a physical many-to-many bridge table.',
          vi: 'TREATAS áp dụng danh mục từ bảng ngân sách làm bộ lọc sang Dim_Products mà không cần tạo bảng cầu nối nhiều-nhiều vật lý.'
        }
      }
    ],
    commonMistakes: [
      {
        mistake: {
          en: 'Adding calculated measure extensions directly inside SUMMARIZE(Table, Col1, "Metric", [Measure]).',
          vi: 'Viết thẳng các measure tính toán bên trong SUMMARIZE(Bảng, Cột1, "ChỉSố", [Measure]).'
        },
        correction: {
          en: 'This is an anti-pattern that can produce silent data calculation errors. Always use SUMMARIZE only for grouping columns, and wrap it in ADDCOLUMNS for calculations.',
          vi: 'Đây là lỗi anti-pattern gây sai lệch kết quả ngầm. Luôn chỉ dùng SUMMARIZE để gom nhóm cột, và bọc bên ngoài bằng ADDCOLUMNS để tính toán measure.'
        }
      },
      {
        mistake: {
          en: 'Using complex INTERSECT and FILTER chains when TREATAS accomplishes virtual filtering in a single optimized VertiPaq step.',
          vi: 'Dùng chuỗi hàm INTERSECT và FILTER rườm rà trong khi TREATAS giải quyết việc lọc ảo chỉ trong 1 bước tối ưu.'
        },
        correction: {
          en: 'TREATAS is heavily optimized inside the storage engine and executes magnitudes faster than legacy table joins.',
          vi: 'TREATAS được tối ưu trực tiếp trong bộ máy lưu trữ VertiPaq nên tốc độ xử lý nhanh vượt trội so với các phép ghép bảng kiểu cũ.'
        }
      }
    ],
    tips: [
      {
        en: 'Use TREATAS when comparing tables at different grains (e.g. Sales at Daily Product grain vs Budget at Monthly Category grain).',
        vi: 'Dùng TREATAS khi so sánh các bảng có độ chi tiết khác nhau (như Bán hàng theo Ngày-Sản phẩm còn Ngân sách theo Tháng-Nhóm hàng).'
      },
      {
        en: 'TOPN(N, Table, OrderExpression, [OrderDirection]) is a high-performance table function to retrieve Top 5 or Top 10 customer/product records dynamically.',
        vi: 'Hàm TOPN(N, Bảng, BiểuThứcSắpXếp, [ChiềuSắpXếp]) là hàm bảng hiệu năng cao để lấy Top 5 hoặc Top 10 khách hàng/sản phẩm xuất sắc nhất.'
      }
    ],
    practiceStarterCode: `// DAX measure applying virtual filter via TREATAS
Budgeted Sales = CALCULATE([Total Sales], TREATAS(VALUES(Fact_Budget[Category]), Dim_Products[Category]))`
  },
  exercisePool: [
    {
      id: 'pbi_ex_15_1',
      type: 'predict_output',
      title: {
        en: 'Identify Role of TREATAS in DAX',
        vi: 'Xác Định Vai Trò Của TREATAS Trong DAX'
      },
      instruction: {
        en: 'What does TREATAS(VALUES(Table1[Key]), Table2[Key]) accomplish inside CALCULATE?',
        vi: 'Hàm TREATAS(VALUES(Table1[Key]), Table2[Key]) làm nhiệm vụ gì bên trong CALCULATE?'
      },
      starterCode: '// Choose TREATAS function outcome',
      solutionCode: 'Injects the values from Table1[Key] as an active virtual filter context on Table2[Key]',
      options: [
        'Injects the values from Table1[Key] as an active virtual filter context on Table2[Key]',
        'Deletes matching keys from Table2',
        'Permanently renames the column in Table2',
        'Creates a physical foreign key constraint in the database'
      ],
      correctOptionIndex: 0,
      explanation: {
        en: 'TREATAS assigns the data lineage and values of an in-memory table directly to one or more model columns, acting as a high-speed virtual relationship.',
        vi: 'TREATAS gán dòng dữ liệu và giá trị của bảng tạm thời vào các cột mô hình, hoạt động như một mối quan hệ ảo tốc độ cao.'
      }
    },
    {
      id: 'pbi_ex_15_2',
      type: 'fix_code',
      title: {
        en: 'Apply Safe ADDCOLUMNS + SUMMARIZE Pattern',
        vi: 'Áp Dụng Mẫu Chuẩn An Toàn ADDCOLUMNS + SUMMARIZE'
      },
      instruction: {
        en: 'Restructure the expression to separate grouping (SUMMARIZE) from measure evaluation (ADDCOLUMNS).',
        vi: 'Tái cấu trúc biểu thức để tách biệt việc gom nhóm (SUMMARIZE) khỏi việc tính toán measure (ADDCOLUMNS).'
      },
      starterCode: 'Result = SUMMARIZE(Sales, Dim_Products[Category], "CatRevenue", [Total Revenue])',
      solutionCode: 'Result = ADDCOLUMNS(SUMMARIZE(Sales, Dim_Products[Category]), "CatRevenue", [Total Revenue])',
      hint: {
        en: 'ADDCOLUMNS(SUMMARIZE(Sales, Dim_Products[Category]), "CatRevenue", [Total Revenue])',
        vi: 'ADDCOLUMNS(SUMMARIZE(Sales, Dim_Products[Category]), "CatRevenue", [Total Revenue])'
      },
      explanation: {
        en: 'Best practice: SUMMARIZE handles grouping columns, and ADDCOLUMNS safely computes the measure in row context.',
        vi: 'Thực hành chuẩn: SUMMARIZE xử lý việc gom nhóm cột, và ADDCOLUMNS tính toán measure an toàn trong ngữ cảnh dòng.'
      }
    }
  ],
  challenge: {
    id: 'pbi_ch_15',
    title: {
      en: 'Architect Virtual Relationship & Top-N Analysis Model',
      vi: 'Xây Dựng Mô Hình Quan Hệ Ảo & Phân Tích Top-N'
    },
    description: {
      en: 'Write two advanced DAX measures: Top 5 Customers Revenue (using TOPN and SUMX), and Budget Variance utilizing TREATAS.',
      vi: 'Viết hai measure DAX nâng cao: Doanh thu Top 5 Khách hàng (dùng TOPN và SUMX) và Chênh lệch Ngân sách dùng TREATAS.'
    },
    requirements: [
      { en: '1. Total Revenue = SUM(Fact_Sales[Revenue])', vi: '1. Total Revenue = SUM(Fact_Sales[Revenue])' },
      { en: '2. Top 5 Customers Revenue = SUMX(TOPN(5, Dim_Customers, [Total Revenue], DESC), [Total Revenue])', vi: '2. Top 5 Customers Revenue = SUMX(TOPN(5, Dim_Customers, [Total Revenue], DESC), [Total Revenue])' },
      { en: '3. Virtual Budgeted Sales = CALCULATE([Total Revenue], TREATAS(VALUES(Fact_Budget[Category]), Dim_Products[Category]))', vi: '3. Virtual Budgeted Sales = CALCULATE([Total Revenue], TREATAS(VALUES(Fact_Budget[Category]), Dim_Products[Category]))' }
    ],
    starterCode: `Total Revenue = SUM(Fact_Sales[Revenue])
Top 5 Customers Revenue = SUMX(TOPN(5, Dim_Customers, [Total Revenue], DESC), [Total Revenue])
Virtual Budgeted Sales = CALCULATE([Total Revenue], TREATAS(VALUES(Fact_Budget[Category]), Dim_Products[Category]))`,
    solutionCode: `Total Revenue = SUM(Fact_Sales[Revenue])
Top 5 Customers Revenue = SUMX(TOPN(5, Dim_Customers, [Total Revenue], DESC), [Total Revenue])
Virtual Budgeted Sales = CALCULATE([Total Revenue], TREATAS(VALUES(Fact_Budget[Category]), Dim_Products[Category]))`,
    hints: [
      {
        en: 'TOPN returns the top 5 customer rows, and SUMX iterates over them to compute their combined revenue.',
        vi: 'TOPN trả về bảng 5 dòng khách hàng dẫn đầu và SUMX duyệt qua để tính tổng doanh thu của họ.'
      }
    ],
    solutionExplanation: {
      en: 'Mastering table functions like TOPN, TREATAS, and SUMMARIZE unlocks advanced enterprise reporting scenarios.',
      vi: 'Làm chủ các hàm bảng như TOPN, TREATAS và SUMMARIZE mở ra các bài toán phân tích quản trị doanh nghiệp chuyên sâu.'
    }
  },
  quizQuestionPool: [
    {
      id: 'pbi_q_15_1',
      type: 'single_choice',
      question: {
        en: 'What is the primary function of TREATAS in DAX?',
        vi: 'Chức năng cốt lõi nhất của hàm TREATAS trong DAX là gì?'
      },
      options: [
        {
          en: 'It applies the result of an in-memory table expression as active filters onto specified columns in the model, creating a virtual relationship',
          vi: 'Áp dụng kết quả của một biểu thức bảng ảo làm bộ lọc lên các cột chỉ định trong mô hình, tạo ra một mối quan hệ ảo'
        },
        {
          en: 'It formats currency numbers with dollar signs',
          vi: 'Định dạng số tiền tệ kèm ký tự đô la'
        },
        {
          en: 'It restarts the Power BI service gateway',
          vi: 'Khởi động lại cổng kết nối gateway'
        },
        {
          en: 'It translates English text into French',
          vi: 'Dịch văn bản tiếng Anh sang tiếng Pháp'
        }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'TREATAS passes data lineage from a source table to target columns, establishing virtual filter propagation without model relationships.',
        vi: 'TREATAS truyền luồng dữ liệu từ bảng nguồn sang các cột đích, thiết lập quan hệ lọc ảo mà không cần tạo liên kết vật lý.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'easy'
    },
    {
      id: 'pbi_q_15_2',
      type: 'single_choice',
      question: {
        en: 'Why is it considered a major DAX anti-pattern to perform measure calculations directly inside SUMMARIZE?',
        vi: 'Vì sao việc tính toán measure trực tiếp bên trong hàm SUMMARIZE lại bị coi là một lỗi anti-pattern nghiêm trọng trong DAX?'
      },
      options: [
        {
          en: 'SUMMARIZE contains known query optimizer clustering bugs that can result in incorrect calculations; always combine ADDCOLUMNS with SUMMARIZE instead',
          vi: 'SUMMARIZE có lỗi tối ưu hóa phân nhóm ngầm có thể dẫn tới kết quả tính toán sai lệch; luôn phải kết hợp ADDCOLUMNS với SUMMARIZE'
        },
        {
          en: 'SUMMARIZE can only be used in Excel, not Power BI',
          vi: 'SUMMARIZE chỉ dùng được trong Excel'
        },
        {
          en: 'SUMMARIZE deletes the primary key columns',
          vi: 'SUMMARIZE xóa các cột khóa chính'
        },
        {
          en: 'There is no bug; the community recommendation is outdated',
          vi: 'Không có lỗi nào; khuyến nghị cộng đồng đã lỗi thời'
        }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'The recommended best practice is: ADDCOLUMNS(SUMMARIZE(Table, GroupColumns...), "MeasureName", [Measure]).',
        vi: 'Mẫu hình chuẩn mực được khuyến nghị là: ADDCOLUMNS(SUMMARIZE(Bảng, CộtGomNhóm...), "TênMeasure", [Measure]).'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'hard'
    },
    {
      id: 'pbi_q_15_3',
      type: 'single_choice',
      question: {
        en: 'Which table function returns the top N rows of a table based on a given ranking expression?',
        vi: 'Hàm bảng nào trả về N dòng đứng đầu của một bảng dựa trên một biểu thức xếp hạng chỉ định?'
      },
      options: [
        { en: 'TOPN()', vi: 'TOPN()' },
        { en: 'LIMIT()', vi: 'LIMIT()' },
        { en: 'HEAD()', vi: 'HEAD()' },
        { en: 'FIRSTN()', vi: 'FIRSTN()' }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'TOPN(N, Table, OrderBy_Expression, [OrderDirection]) returns a table with the top N rows.',
        vi: 'TOPN(N, Bảng, BiểuThứcSắpXếp, [ChiềuSắpXếp]) trả về một bảng gồm N dòng dẫn đầu.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'easy'
    },
    {
      id: 'pbi_q_15_4',
      type: 'true_false',
      question: {
        en: 'VALUES(Dim_Products[Category]) includes the blank row added when foreign keys in the fact table have no match in the dimension table.',
        vi: 'Hàm VALUES(Dim_Products[Category]) bao gồm cả dòng trống (blank row) phát sinh khi khóa ngoại trong bảng fact không tìm thấy bản ghi tương ứng trong bảng dimension.'
      },
      options: [
        { en: 'True', vi: 'Đúng' },
        { en: 'False', vi: 'Sai' }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'True. VALUES respects the referential integrity blank row, whereas DISTINCT ignores the blank row unless blank is explicitly present in the column.',
        vi: 'Đúng. VALUES bảo toàn dòng blank toàn vẹn quan hệ, trong khi DISTINCT bỏ qua dòng blank này trừ khi dữ liệu gốc thực sự chứa giá trị blank.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'hard'
    },
    {
      id: 'pbi_q_15_5',
      type: 'predict_output',
      question: {
        en: 'What does CROSSJOIN(TableA, TableB) return if TableA has 3 rows and TableB has 4 rows?',
        vi: 'Hàm CROSSJOIN(TableA, TableB) trả về bảng có bao nhiêu dòng nếu TableA có 3 dòng và TableB có 4 dòng?'
      },
      options: [
        { en: '12 rows (Cartesian product: 3 * 4)', vi: '12 dòng (Tích Descartes: 3 * 4)' },
        { en: '7 rows (3 + 4)', vi: '7 dòng (3 + 4)' },
        { en: '1 row', vi: '1 dòng' },
        { en: '0 rows', vi: '0 dòng' }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'CROSSJOIN produces the Cartesian product of all rows from TableA with all rows from TableB (3 * 4 = 12).',
        vi: 'CROSSJOIN tạo tích Descartes kết hợp từng dòng của TableA với tất cả các dòng của TableB (3 * 4 = 12 dòng).'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'easy'
    },
    {
      id: 'pbi_q_15_6',
      type: 'multiple_choice',
      question: {
        en: 'Which of the following are DAX table functions that return tables rather than single scalar values? (Select all that apply)',
        vi: 'Những hàm nào sau đây là các hàm bảng trong DAX trả về một bảng thay vì một giá trị đơn lẻ? (Chọn tất cả đáp án đúng)'
      },
      options: [
        { en: 'FILTER()', vi: 'FILTER()' },
        { en: 'ALL()', vi: 'ALL()' },
        { en: 'SUMMARIZE()', vi: 'SUMMARIZE()' },
        { en: 'DIVIDE()', vi: 'DIVIDE()' }
      ],
      correctAnswers: [0, 1, 2],
      explanation: {
        en: 'FILTER, ALL, and SUMMARIZE return tables. DIVIDE returns a scalar numeric value.',
        vi: 'FILTER, ALL và SUMMARIZE là các hàm trả về bảng. DIVIDE trả về một số đơn lẻ.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'easy'
    },
    {
      id: 'pbi_q_15_7',
      type: 'single_choice',
      question: {
        en: 'What does the GENERATE() function do in DAX?',
        vi: 'Hàm GENERATE() thực hiện nhiệm vụ gì trong DAX?'
      },
      options: [
        {
          en: 'Evaluates the second table expression for each row of the first table, returning a cross-joined combination of the results',
          vi: 'Đánh giá biểu thức bảng thứ hai cho từng dòng của bảng thứ nhất và trả về bảng kết hợp dạng tích chéo của các kết quả'
        },
        {
          en: 'Generates random test data for reports',
          vi: 'Tạo dữ liệu thử nghiệm ngẫu nhiên'
        },
        {
          en: 'Generates a PDF export of all pages',
          vi: 'Xuất toàn bộ trang ra tệp PDF'
        },
        {
          en: 'Generates AI summaries automatically',
          vi: 'Tự động tạo tóm tắt bằng AI'
        }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'GENERATE loops over Table1 and evaluates Table2 in that row context, returning the combined table.',
        vi: 'GENERATE duyệt qua từng dòng của Table1 và đánh giá Table2 trong ngữ cảnh dòng đó, trả về bảng kết hợp.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'medium'
    },
    {
      id: 'pbi_q_15_8',
      type: 'true_false',
      question: {
        en: 'TREATAS is significantly faster and consumes less memory than establishing a physical Many-to-Many relationship with a bridge table in many scenarios.',
        vi: 'TREATAS chạy nhanh hơn rõ rệt và tiêu tốn ít bộ nhớ hơn việc tạo quan hệ Nhiều-Nhiều vật lý kèm bảng cầu nối trong nhiều trường hợp.'
      },
      options: [
        { en: 'True', vi: 'Đúng' },
        { en: 'False', vi: 'Sai' }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'True. TREATAS operates purely at query time inside the VertiPaq engine without materializing bridge tables or maintaining bi-directional relationship graphs.',
        vi: 'Đúng. TREATAS hoạt động thuần túy tại thời điểm truy vấn trong VertiPaq mà không cần tạo bảng cầu nối hay duy trì đồ thị quan hệ 2 chiều.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'medium'
    },
    {
      id: 'pbi_q_15_9',
      type: 'predict_output',
      question: {
        en: 'What does the DAX measure: Top 3 Sales = SUMX(TOPN(3, Dim_Products, [Total Sales], DESC), [Total Sales]) calculate?',
        vi: 'Measure DAX: Top 3 Sales = SUMX(TOPN(3, Dim_Products, [Total Sales], DESC), [Total Sales]) tính giá trị gì?'
      },
      options: [
        {
          en: 'The combined total sales of the top 3 best-selling products',
          vi: 'Tổng doanh thu kết hợp của 3 sản phẩm bán chạy nhất'
        },
        {
          en: 'The sales of the 3rd product only',
          vi: 'Chỉ doanh số của sản phẩm đứng thứ 3'
        },
        {
          en: 'Three times the average sales',
          vi: 'Gấp 3 lần doanh số trung bình'
        },
        {
          en: 'Deletes all products except the top 3',
          vi: 'Xóa toàn bộ sản phẩm ngoại trừ top 3'
        }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'TOPN retrieves the top 3 products ranked by [Total Sales], and SUMX calculates their collective revenue.',
        vi: 'TOPN lấy ra 3 sản phẩm có [Total Sales] cao nhất và SUMX tính tổng doanh thu của 3 sản phẩm đó.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'easy'
    },
    {
      id: 'pbi_q_15_10',
      type: 'single_choice',
      question: {
        en: 'What function is used to create a table with a single column containing a sequence of numbers (e.g. from 1 to 100 with step 1)?',
        vi: 'Hàm nào dùng để tạo một bảng 1 cột chứa chuỗi số liên tiếp (như từ 1 đến 100 với bước nhảy 1)?'
      },
      options: [
        { en: 'GENERATESERIES()', vi: 'GENERATESERIES()' },
        { en: 'NUMBER_RANGE()', vi: 'NUMBER_RANGE()' },
        { en: 'SERIES()', vi: 'SERIES()' },
        { en: 'COUNT_UP()', vi: 'COUNT_UP()' }
      ],
      correctAnswers: [0],
      explanation: {
        en: 'GENERATESERIES(StartValue, EndValue, [IncrementValue]) generates a single-column table named [Value] of sequential numbers.',
        vi: 'GENERATESERIES(StartValue, EndValue, [IncrementValue]) tạo một bảng 1 cột có tên là [Value] chứa dãy số tuần tự.'
      },
      topicId: 'dax_advanced_table_functions',
      difficulty: 'easy'
    }
  ]
};

export default lesson15;
