import { RawQ, RawEx } from '../banks/topicsData';
import { q, ex } from '../questionHelper';

export const group1Banks: Record<number, { questions: RawQ[]; exercises: RawEx[] }> = {};

// Lesson 1: python_foundations
group1Banks[1] = {
  questions: [
    q("Who created Python and in what year was it first released?", "Ai là người sáng tạo ra ngôn ngữ Python và năm phát hành đầu tiên là năm nào?",
      [["Guido van Rossum in 1991", "Guido van Rossum năm 1991"], ["Dennis Ritchie in 1972", "Dennis Ritchie năm 1972"], ["James Gosling in 1995", "James Gosling năm 1995"], ["Bjarne Stroustrup in 1985", "Bjarne Stroustrup năm 1985"]],
      [0], "Python was created by Guido van Rossum and released in 1991.", "Python do Guido van Rossum sáng tạo và phát hành năm 1991.", "easy"),
    q("What is Python bytecode?", "Bytecode trong Python là gì?",
      [["Platform-independent intermediate code executed by the Python Virtual Machine (PVM)", "Mã trung gian độc lập nền tảng được Máy ảo Python (PVM) thực thi"], ["Direct binary machine code compiled for hardware", "Mã máy nhị phân chạy trực tiếp trên phần cứng"], ["The original source code stored in .py files", "Mã nguồn gốc lưu trong tệp .py"], ["A JavaScript representation of Python syntax", "Biểu diễn JavaScript của cú pháp Python"]],
      [0], "Python source code is compiled to intermediate bytecode (.pyc) for the PVM.", "Mã nguồn Python được biên dịch thành bytecode trung gian (.pyc) cho PVM.", "easy"),
    q("What does REPL stand for?", "Thuật ngữ REPL viết tắt của cụm từ nào?",
      [["Read-Eval-Print Loop", "Read-Eval-Print Loop (Đọc-Đánh giá-In-Lặp)"], ["Runtime Execution Program Logic", "Runtime Execution Program Logic"], ["Recursive Evaluation Process Level", "Recursive Evaluation Process Level"], ["Realtime Environment Parser Link", "Realtime Environment Parser Link"]],
      [0], "REPL is the interactive shell environment in Python.", "REPL là môi trường dòng lệnh tương tác của Python.", "easy"),
    q("How are single-line comments denoted in Python?", "Chú thích dòng đơn trong Python được bắt đầu bằng ký tự nào?",
      [["# (Hash/Octothorpe)", "Dấu #"], ["// (Double slash)", "Dấu //"], ["-- (Double dash)", "Dấu --"], ["/* (Slash star)", "Dấu /*"]],
      [0], "Python uses # for single-line comments.", "Python dùng dấu # cho chú thích dòng đơn.", "easy"),
    q("What command displays The Zen of Python?", "Lệnh nào hiển thị triết lý thiết kế The Zen of Python?",
      [["import this", "import this"], ["import zen", "import zen"], ["help(zen)", "help(zen)"], ["print(ZEN)", "print(ZEN)"]],
      [0], "'import this' prints the 19 aphorisms of Python design philosophy.", "'import this' in ra 19 triết lý thiết kế của Python.", "easy"),
    q("Which file extension holds compiled Python bytecode?", "Phần mở rộng nào chứa tệp bytecode đã biên dịch của Python?",
      [[".pyc", ".pyc"], [".py", ".py"], [".pyd", ".pyd"], [".class", ".class"]],
      [0], ".pyc files store cached bytecode.", ".pyc chứa bytecode được lưu đệm trong __pycache__.", "medium"),
    q("What component executes bytecode instructions line-by-line?", "Thành phần nào thực thi các chỉ lệnh bytecode trong Python?",
      [["Python Virtual Machine (PVM)", "Máy ảo Python (PVM)"], ["CPU Hardware direct register", "Thanh ghi phần cứng CPU trực tiếp"], ["Operating System kernel scheduler", "Bộ điều phối kernel hệ điều hành"], ["V8 JavaScript engine", "Engine JavaScript V8"]],
      [0], "The PVM is the runtime interpreter of compiled bytecode.", "PVM là máy ảo diễn giải và chạy bytecode.", "medium"),
    q("Why does Python enforce indentation?", "Tại sao Python bắt buộc dùng thụt đầu dòng (indentation)?",
      [["To enforce uniform structure and visual readability without braces", "Để bắt buộc cấu trúc đồng nhất và dễ đọc mà không cần ngoặc nhọn"], ["Because indentation speeds up compilation by 10x", "Vì thụt đầu dòng tăng tốc biên dịch gấp 10 lần"], ["Because older keyboards lacked curly braces", "Vì bàn phím cũ thiếu phím ngoặc nhọn"], ["Indentation is purely cosmetic and optional", "Thụt lề chỉ để trang trí và không bắt buộc"]],
      [0], "Indentation defines block scope in Python, replacing curly braces.", "Thụt đầu dòng xác định khối lệnh trong Python, thay thế cho dấu ngoặc nhọn.", "medium"),
    q("What is CPython?", "CPython là gì?",
      [["The standard, reference implementation of Python written in C", "Bản triển khai tham chiếu tiêu chuẩn của Python viết bằng C"], ["A compiler that converts C to Python", "Trình biên dịch mã C sang Python"], ["A Python library for microcontrollers", "Thư viện Python cho vi điều khiển"], ["A closed-source proprietary distribution", "Một bản phân phối mã nguồn đóng thương mại"]],
      [0], "CPython is the reference implementation distributed at python.org.", "CPython là bản triển khai tham chiếu chuẩn của Python.", "medium"),
    q("Which built-in function writes text to standard output?", "Hàm tích hợp sẵn nào xuất văn bản ra màn hình console?",
      [["print()", "print()"], ["echo()", "echo()"], ["display()", "display()"], ["console.log()", "console.log()"]],
      [0], "print() outputs text and variables to stdout.", "print() xuất chuỗi và giá trị ra luồng stdout.", "easy"),
    q("What happens when a Python script has a SyntaxError?", "Điều gì xảy ra khi mã nguồn Python có lỗi SyntaxError?",
      [["It fails during parsing before running any code", "Chương trình dừng ngay ở bước phân tích cú pháp trước khi thực thi bất kỳ dòng mã nào"], ["It runs up to the bad line and then crashes", "Chương trình chạy đến dòng lỗi rồi mới dừng"], ["It auto-corrects the error and proceeds", "Tự động sửa lỗi và chạy tiếp"], ["It prints a warning but does not stop", "In cảnh báo nhưng vẫn chạy tiếp"]],
      [0], "Syntax errors prevent bytecode compilation entirely.", "Lỗi cú pháp khiến chương trình không thể biên dịch ra bytecode.", "hard"),
    q("How does Python categorize typing discipline?", "Python thuộc loại ngôn ngữ định kiểu nào?",
      [["Dynamically and strongly typed", "Định kiểu động và định kiểu mạnh (dynamically & strongly typed)"], ["Statically and weakly typed", "Định kiểu tĩnh và định kiểu yếu"], ["Dynamically and weakly typed", "Định kiểu động và định kiểu yếu"], ["Purely untyped", "Hoàn toàn không có kiểu"]],
      [0], "Python is dynamically typed (types bound at runtime) and strongly typed (no silent coercive conversions like '5' + 5).", "Python định kiểu động (gán kiểu lúc chạy) và định kiểu mạnh (không tự ép kiểu bừa bãi như '5' + 5).", "medium"),
    q("Where are compiled .pyc files cached by default in Python 3?", "Trong Python 3, các tệp bytecode .pyc mặc định được lưu trong thư mục nào?",
      [["__pycache__ directory", "Thư mục __pycache__"], [".bin directory", "Thư mục .bin"], ["/tmp/python directory", "Thư mục /tmp/python"], ["In the root directory alongside .py", "Cùng cấp trong thư mục gốc"]],
      [0], "Python 3 stores cached bytecode in __pycache__.", "Python 3 gom bytecode vào thư mục __pycache__.", "medium"),
    q("Which module provides interpreter runtime info like sys.version?", "Mô-đun nào cung cấp thông tin hệ thống và phiên bản Python?",
      [["sys", "sys"], ["os", "os"], ["platform", "platform"], ["env", "env"]],
      [0], "sys module gives direct access to interpreter parameters.", "Mô-đun sys cung cấp các thông số của trình thông dịch.", "easy"),
    q("What does PEP stand for in Python development?", "Thuật ngữ PEP trong hệ sinh thái Python viết tắt của gì?",
      [["Python Enhancement Proposal", "Python Enhancement Proposal (Đề xuất Cải tiến Python)"], ["Program Execution Protocol", "Program Execution Protocol"], ["Python Error Prevention", "Python Error Prevention"], ["Package Extension Process", "Package Extension Process"]],
      [0], "PEPs are design documents for Python features and standards.", "PEP là các tài liệu đề xuất tính năng và tiêu chuẩn cho Python (như PEP 8).", "medium"),
    q("What is PEP 8?", "PEP 8 là tiêu chuẩn gì trong Python?",
      [["The official Style Guide for Python Code", "Hướng dẫn chuẩn phong cách viết mã nguồn Python (Style Guide)"], ["The Python compiler specification", "Đặc tả kỹ thuật của trình biên dịch Python"], ["The memory management protocol", "Giao thức quản lý bộ nhớ của Python"], ["The asyncio standard library specification", "Đặc tả thư viện bất đồng bộ asyncio"]],
      [0], "PEP 8 specifies naming conventions, 4-space indentation, line length, etc.", "PEP 8 quy định quy chuẩn đặt tên, thụt lề 4 dấu cách, độ dài dòng, v.v.", "easy")
  ],
  exercises: [
    ex('fix_code', "Fix Case-Sensitive Print Function", "Sửa Lỗi Hàm Print Viết Hoa",
      "Change Print to lowercase print to fix the NameError.", "Đổi Print thành chữ thường print để sửa lỗi NameError.",
      'Print("Welcome to 4TM Python!")', 'print("Welcome to 4TM Python!")',
      "Use lowercase print()", "Dùng hàm print() chữ thường",
      "Built-in functions in Python are case-sensitive and lowercase.", "Các hàm tích hợp sẵn trong Python bắt buộc phải viết chữ thường."),
    ex('complete_code', "Output Two Computed Values", "In Hai Giá Trị Tính Toán",
      "Complete the print call to output the result of 15 * 4.", "Hoàn thiện lệnh print để in ra kết quả phép nhân 15 * 4.",
      'print("Result is:", )', 'print("Result is:", 15 * 4)',
      "Pass 15 * 4 as the second argument.", "Truyền 15 * 4 làm tham số thứ hai.",
      "print() accepts multiple comma-separated arguments.", "print() có thể nhận nhiều tham số ngăn cách bởi dấu phẩy."),
    ex('write_code', "Print System Banner", "In Biểu Ngữ Hệ Thống",
      "Write a print statement that outputs '=== 4TM Python Engine Active ==='.", "Viết lệnh print in ra dòng chữ '=== 4TM Python Engine Active ==='.",
      '# Write your code below:\n', 'print("=== 4TM Python Engine Active ===")',
      "Use print with the exact string.", "Dùng print với chuỗi ký tự chính xác.",
      "print() writes the specified string to standard output followed by a newline.", "print() xuất chuỗi ra stdout và kết thúc bằng ký tự xuống dòng."),
    ex('predict_output', "Predict Python Version Output", "Dự Đoán Đầu Ra",
      "Complete the code to import sys and print sys.platform.", "Hoàn thiện mã để nạp mô-đun sys và in sys.platform.",
      'import sys\n# print platform below\n', 'import sys\nprint(sys.platform)',
      "Use print(sys.platform)", "Dùng print(sys.platform)",
      "sys.platform indicates the underlying operating system platform.", "sys.platform cho biết nền tảng hệ điều hành đang chạy."),
    ex('problem_solving', "Calculate and Display Ellipse Area", "Tính và In Diện Tích Hình Elip",
      "Given a = 7 and b = 4, compute area = 3.14159 * a * b and print 'Area: ' followed by the rounded area.", "Cho a = 7 và b = 4, tính area = 3.14159 * a * b và in 'Area: ' kèm diện tích làm tròn 2 chữ số.",
      'a = 7\nb = 4\n# Calculate area and print\n', 'a = 7\nb = 4\narea = round(3.14159 * a * b, 2)\nprint("Area:", area)',
      "Formula is 3.14159 * a * b", "Công thức là 3.14159 * a * b",
      "Variables store intermediate numeric computations cleanly.", "Biến số lưu trữ kết quả tính toán số học rõ ràng.")
  ]
};

console.log("Group 1 bank initialized.");
